sudo: required
services:
  - docker

before_install:
  - docker build -t asylumrunner/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true asylumrunner/docker-react npm run test -- --coverage
